### ISSUE TITLE
IndexError: too many indices for array

### ISSUE THREAD

**Issue by ghost** [atgambardella/pytorch-es#10]
Hi,

I trying to run cartpole using this command

```
python3 main.py --small-net --env-name CartPole-v1
```

and I get a screen full of errors like this

```
IndexError: too many indices for array
Process Process-41:
Traceback (most recent call last):
  File "/home/ajay/anaconda3/envs/py35_pytorch/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/ajay/anaconda3/envs/py35_pytorch/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/ajay/PythonProjects/pytorch-es-master/train.py", line 49, in do_rollouts
    state, reward, done, _ = env.step(action[0, 0])
IndexError: too many indices for array
```

**Comment by atgambardella** [comment]
Are you using a recent version of PyTorch? My code was written for 0.1.x and some things broke in the most recent version. I think changing that line to

`state, reward, done, _ = env.step(action[0])`

would most likely fix it.

**Comment by ghost** [comment]
Hi, thanks very much - that seems to have go it working,

```
(py35_pytorch) ajay@ajay-h8-1170uk:~/PythonProjects/pytorch-es-master$ python main.py --small-net --env-name CartPole-v0
[2017-09-10 10:42:02,300] Making new env: CartPole-v0
No preprocessing because env is too small
Num params in network 4610
Episode num: 40
Average reward: 26.025000
Variance in rewards: 1738.724375
Max reward: 199.000000
Min reward: 9.000000
Batch size: 40
Max episode length: 100000
Sigma: 0.050000
Learning rate: 0.300000
Total num frames seen: 1041
Unperturbed reward: 11.000000
Unperturbed rank: 19 out of 41 (1 means gradient is uninformative)
Using Adam: False
```

Looks like it "converges" to the max reward.

```
Episode num: 1200
Average reward: 191.350000
Variance in rewards: 1272.527500
Max reward: 200.000000
Min reward: 14.000000
Batch size: 40
Max episode length: 100000
Sigma: 0.050000
Learning rate: 0.300000
Total num frames seen: 201716
Unperturbed reward: 200.000000
Unperturbed rank: 1 out of 41 (1 means gradient is uninformative)
Using Adam: False
```

I think we can close this if you're happy?
